name: CD Front-end


on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
    
jobs:
  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend-main.yml
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Railway