name: CD Front-end


on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
    
jobs:
  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend-main.yml
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Railway
    steps:
      - name: Checkout  
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        working-directory: front-end/
        run: npm run build --prod
      - name: Instalação do cliente Railway
        run: npm install -g @railway/cli
      - name: Deploy
        working-directory: front-end/dist/sgcmapp/
        run: railway up --detach --service sgcm
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}