name: CI Back-end

on:
  push:
    branches:
      - 'main'
      - 'teste'
    paths:
      - 'back-end/**'
  pull_request:
    paths:
      - '**'
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compilação / Test / Package
        working-directory: back-end/
        run: mvn --activate-profiles prod package
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      # - name: Compilação / Test / Package
      #   working-directory: back-end/
      #   run: mvn --activate-profiles prod package
