name: CI Front-end

on:
  # permite que execute o workflow a partir do github
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'front-end/**'
  pull_request:
    paths:
      - 'front-end/**'
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compilação / Teste
        working-directory: front-end/
        run: npm install
      - name: Teste aplicação
        run: npm run test
      - name: Build Projeto
        run: npm run build
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install CLI Angular
        uses: npm install -g @angular/cli
      - name: Install with npm
        working-directory: front-end/
        run: npm install
      - name: Build for production
        run: npm run build --prod